[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }

size = 10.0

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 1
padding = { x = 0, y = 0 }
decorations = "None"
blur = true

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" }
]


# Colors (Ayu Mirage)

# Default Colors
[colors.primary]
background = "#1f2430"
foreground = "#cbccc6"
bright_foreground = "#f28779"

# Normal colors
[colors.normal]
black = "#212733"
red = "#f08778"
green = "#53bf97"
yellow = "#fdcc60"
blue = "#60b8d6"
magenta = "#ec7171"
cyan = "#98e6ca"
white = "#fafafa"

# Bright colors
[colors.bright]
black = "#686868"
red = "#f58c7d"
green = "#58c49c"
yellow = "#ffd165"
blue = "#65bddb"
magenta = "#f17676"
cyan = "#9debcf"
white = "#ffffff"

[colors]
draw_bold_text_with_bright_colors = true 
transparent_background_colors = true
